CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL
);
INSERT INTO usuarios (email, password) VALUES ('usuario@teste.com', 'senha123');
